[package]
name = "hallopoint2"
version = "0.1.0"
authors = ["tasgon <tasgon_@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acidalia = { path = "../acidalia/" }
image = "0.23"
nfd2 = "0.3"